### ISSUE TITLE
HWE for WES

### ISSUE THREAD

**Issue by Shicheng-Guo** [ESR-NZ/human_genomics_pipeline#21]
Is there any suggestive HWE cut-off for large-scale WES?

**Comment by jdeligt** [comment]
Hi Shicheng-Guo,

Thanks for reaching out, I just don't know if this is the best place to ask such a question (sites like researchgate has a pretty section for these types of questions: https://www.researchgate.net/topics) and for futher reading this might be a good place to start: https://www.frontiersin.org/articles/10.3389/fgene.2020.00210/full.

Things to account for when using WES data is the fact that evolutionary rates are different in gene bodies vs genome wide, and dependent on your populations distance from the reference genome, so in short there is not 1 answer to your question. 

Since your question is not an issue with the pipeline I will close it off too keep things tidy.

All the best and take care,
Joep
